title: Contact Manager
email: your-email@example.com
description: >- 
  A simple contact management site powered by Jekyll.
baseurl: "" # 根目录，无需子目录
url: "https://yourusername.github.io" # 替换为您的 GitHub Pages URL
twitter_username: your_twitter
github_username: your_github

markdown: kramdown
theme: minima # Jekyll 默认主题，您也可以替换为其他主题
