title: My Jekyll Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple description of your site.
baseurl: "" # 如果直接部署在根目录，保持为空字符串
url: "https://yourusername.github.io" # 替换为你的 GitHub Pages URL
twitter_username: your_twitter_username
github_username: your_github_username

# 可选的额外配置
markdown: kramdown
theme: minima
